/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EssayageVirtuelRouteImport } from './routes/essayage-virtuel'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as ProduitsRouteImport } from './routes/produits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayageVirtuelRoute = EssayageVirtuelRouteImport.update({
  id: '/essayage-virtuel',
  path: '/essayage-virtuel',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/essayage-virtuel': typeof EssayageVirtuelRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/produits': typeof ProduitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/essayage-virtuel': typeof EssayageVirtuelRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/produits': typeof ProduitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/essayage-virtuel': typeof EssayageVirtuelRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/produits': typeof ProduitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/avis'
    | '/consultation'
    | '/contact'
    | '/essayage-virtuel'
    | '/mentions-legales'
    | '/partenaires'
    | '/produits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/avis'
    | '/consultation'
    | '/contact'
    | '/essayage-virtuel'
    | '/mentions-legales'
    | '/partenaires'
    | '/produits'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/avis'
    | '/consultation'
    | '/contact'
    | '/essayage-virtuel'
    | '/mentions-legales'
    | '/partenaires'
    | '/produits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AvisRoute: typeof AvisRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  EssayageVirtuelRoute: typeof EssayageVirtuelRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PartenairesRoute: typeof PartenairesRoute
  ProduitsRoute: typeof ProduitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essayage-virtuel': {
      id: '/essayage-virtuel'
      path: '/essayage-virtuel'
      fullPath: '/essayage-virtuel'
      preLoaderRoute: typeof EssayageVirtuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AvisRoute: AvisRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  EssayageVirtuelRoute: EssayageVirtuelRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PartenairesRoute: PartenairesRoute,
  ProduitsRoute: ProduitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
